### ISSUE TITLE
DSUManager doesn't start

### ISSUE THREAD

**Issue by Ivan951236** [breeze2/dsu-manager-guides#2]
When i try to open the DSUManager thing in both admin and non-admin perms i still can't start it

https://github.com/breeze2/dsu-manager-guides/assets/101629412/f9e52a3d-f5fe-4b02-a96a-572c8b494daf

Yes ViGemBUS driver is installed

**Comment by breeze2** [comment]
Was it always like this? DSUManager is not code signed and may be blocked by the system.
Try: right click -> properties -> check unblock if you see "Security: This file came from another computer and might be blocked to help protect this computer".

**Comment by Ivan951236** [comment]
> Was it always like this? DSUManager is not code signed and may be blocked by the system. Try: right click -> properties -> check unblock if you see "Security: This file came from another computer and might be blocked to help protect this computer".

I meant the Installed DSUManager (with shortcut) not Installer, also the exe installed in the directory is already unblocked

**Comment by breeze2** [comment]
What version is your Windows? 
DSUManager needs WebView2 runtime. Try to download and install it: https://developer.microsoft.com/en-us/microsoft-edge/webview2?form=MA13LH#download

**Comment by Ivan951236** [comment]
> What version is your Windows? DSUManager needs WebView2 runtime. Try to download and install it: https://developer.microsoft.com/en-us/microsoft-edge/webview2?form=MA13LH#download

By the looks of the first post's video its Windows 10 21H2 (OS Build 19044.3803)
Edit: The installer reports that its already installed

**Comment by breeze2** [comment]
Is Webview2 installed?

https://support.templafy.com/hc/en-us/articles/360017470437-How-to-check-for-and-install-WebView2

**Comment by breeze2** [comment]
Try to run DSUManager.exe in CMD.exe and see what it outputs.
Just drag it into the CMD window and press Enter.

**Comment by Ivan951236** [comment]
nvm breeze2, it works, i can now start it
