### ISSUE TITLE
DSU manager cannot be installed on PC

### ISSUE THREAD

**Issue by MrA4312** [breeze2/dsu-manager-guides#3]
So when I open the installation wizard to install it, it just says the application is still open when I haven't even installed it yet!
![image](https://github.com/breeze2/dsu-manager-guides/assets/167156037/f03ced26-b676-4951-a5b5-a583374ddf56)
And then if I click ok, this happens:
![image (1)](https://github.com/breeze2/dsu-manager-guides/assets/167156037/fe646dd9-9720-4fe5-8021-de1f5ff64010)
But if I don't click ok, then this happens:
![image (2)](https://github.com/breeze2/dsu-manager-guides/assets/167156037/b14e465b-f7e4-4b88-bcc0-c7779f446dc3)
I don't know what to do.

**Comment by breeze2** [comment]
It's the same problem as this，https://github.com/tauri-apps/nsis-tauri-utils/issues/16#issuecomment-1678217309

Please try to intall the x86 version of the latest [vc_redist](https://aka.ms/vs/17/release/vc_redist.x86.exe).

**Comment by MrA4312** [comment]
Already did, but the installer did the exact same thing. Or do I have to restart my computer first?

**Comment by breeze2** [comment]
Is it a problem with the nsis ? How about the [msi](https://github.com/breeze2/dsu-manager-guides/releases/download/v0.5.0/DSUManager_0.5.0_x64_en-US.msi) ？

**Comment by MrA4312** [comment]
I don't know, but isn't the installer itself supposed to work just fine with no errors?

**Comment by breeze2** [comment]
It can be installed successfully on my computer.
Have you try the [msi](https://github.com/breeze2/dsu-manager-guides/releases/download/v0.5.0/DSUManager_0.5.0_x64_en-US.msi) installer ?
How about  remove the `C:\Users\Aaron\AppData\Local\Temp\nsz4959.tmp\nsis_tauri _utils.dll` or restart computer, and then install it again ?

**Comment by MrA4312** [comment]
Ok the msi works thank you
